//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 serialCommunication.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SERIALCOMMUNICATION_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       130
#define IDB_BITMAP_LOGO                 139
#define IDB_BITMAP_NG                   140
#define IDB_BITMAP_OK                   141
#define IDC_COMBO_PORT_SELECT           1000
#define IDC_COMBO_BAUD_SELECT           1001
#define IDC_COMBO_DATA_BIT_SELECT       1002
#define IDC_COMBO_STOP_SELECT           1003
#define IDC_COMBO_CHECK_SELECT          1004
#define IDC_BUTTON_SERIAL_CONTROL       1005
#define IDC_EDIT_RECEIVE                1006
#define IDC_BUTTON_RECEIVE_SAVE_FILE    1007
#define IDC_BUTTON_RECEIVE_CLEAR        1008
#define IDC_EDIT_SEND                   1009
#define IDC_BUTTON_SEND_FILE            1010
#define IDC_BUTTON_SEND_CLEAR           1011
#define IDC_BUTTON_SEND                 1012
#define IDC_COMBO1                      1015
#define IDC_COMBO_CONFIG_FILE_SELECT    1015
#define IDC_COMBO_DELAY                 1015
#define IDC_COMBO_LAST_SOURCE           1015
#define IDC_BUTTON6                     1016
#define IDC_BUTTON_LOAD_CONFIG_FILE     1016
#define IDC_BUTTON7                     1017
#define IDC_BUTTON_SHORT1               1017
#define IDC_BUTTON8                     1018
#define IDC_BUTTON_SHORT2               1018
#define IDC_BUTTON9                     1019
#define IDC_BUTTON_SHORT3               1019
#define IDC_BUTTON10                    1020
#define IDC_BUTTON_SHORT4               1020
#define IDC_BUTTON11                    1021
#define IDC_BUTTON_SHORT5               1021
#define IDC_BUTTON12                    1022
#define IDC_BUTTON_SHORT6               1022
#define IDC_BUTTON13                    1023
#define IDC_BUTTON_SHORT7               1023
#define IDC_BUTTON14                    1024
#define IDC_BUTTON_SHORT8               1024
#define IDC_LIST1                       1025
#define IDC_BUTTON_LOAD_CONFIG_FILE2    1025
#define IDC_BUTTON15                    1026
#define IDC_BUTTON_SEND_SHORT_FUCTION   1026
#define IDC_BUTTON16                    1027
#define IDC_BUTTON_ADD_FUNC             1027
#define IDC_BUTTON17                    1028
#define IDC_BUTTON_DELFUNC              1028
#define IDC_BUTTON18                    1029
#define IDC_BUTTON_SEND_SELECT_SHORT    1029
#define IDC_BUTTON19                    1030
#define IDC_BUTTON_DEFAULT              1030
#define IDC_EDIT3                       1031
#define IDC_EDIT_FUNC_SEL               1031
#define IDC_EDIT_FAILED                 1031
#define IDC_COMBO2                      1032
#define IDC_COMBO_SEND_STRING_CONFIG    1032
#define IDC_BUTTON_SHORT9               1033
#define IDC_BUTTON_SHORT10              1034
#define IDC_BUTTON_SHORT11              1035
#define IDC_BUTTON_SHORT12              1036
#define IDC_BUTTON_SHORT13              1037
#define IDC_BUTTON_SHORT14              1038
#define IDC_BUTTON_SHORT15              1039
#define IDC_BUTTON_SHORT16              1040
#define IDC_BUTTON_SHORT17              1041
#define IDC_BUTTON_SHORT18              1042
#define IDC_BUTTON_SHORT19              1043
#define IDC_BUTTON_SHORT20              1044
#define IDC_BUTTON_SHORT21              1045
#define IDC_BUTTON_SHORT22              1046
#define IDC_BUTTON_SHORT23              1047
#define IDC_BUTTON_SHORT24              1048
#define IDC_BUTTON_SHORT25              1049
#define IDC_BUTTON_SHORT26              1050
#define IDC_BUTTON_SHORT27              1051
#define IDC_BUTTON_SHORT28              1052
#define IDC_BUTTON_SHORT29              1053
#define IDC_BUTTON_SHORT30              1054
#define IDC_BUTTON_SHORT31              1055
#define IDC_BUTTON_SHORT32              1056
#define IDC_BUTTON_SHORT33              1057
#define IDC_BUTTON_SHORT34              1058
#define IDC_BUTTON_SHORT35              1059
#define IDC_BUTTON_SHORT36              1060
#define IDC_BUTTON_SHORT37              1061
#define IDC_BUTTON_SHORT38              1062
#define IDC_BUTTON_SHORT39              1063
#define IDC_BUTTON_SHORT40              1064
#define IDC_EDIT1                       1065
#define IDC_BUTTON_SHORT41              1066
#define IDC_BUTTON_SHORT42              1067
#define IDC_BUTTON3                     1069
#define IDC_BUTTON_TEST_STOP            1070
#define IDC_BUTTON_SHORT43              1071
#define IDC_BUTTON_SHORT44              1072
#define IDC_BUTTON_SHORT45              1073
#define IDC_BUTTON_SHORT46              1074
#define IDC_BUTTON_SHORT47              1075
#define IDC_BUTTON_SHORT48              1076
#define IDC_TEST_RESUILT                1079
#define IDC_STATIC_PICTURE              1080
#define IDC_BUTTON_SOURCE               1082
#define IDC_BUTTON_MENU                 1083
#define IDC_BUTTON_CHP                  1084
#define IDC_BUTTON_CHM                  1085
#define IDC_BUTTON_VOLP                 1086
#define IDC_BUTTON_POWER                1087
#define IDC_BUTTON_VOLM                 1088
#define IDC_EDIT_VERSION                1089
#define IDC_EDIT2                       1090
#define IDC_EDIT_COLORTMP               1090
#define IDC_EDIT_SETTIME_DTV1           1090
#define IDC_CHECK_WB                    1091
#define IDC_EDIT_SETTIME_DTV2           1091
#define IDC_EDIT4                       1092
#define IDC_EDIT_OK                     1092
#define IDC_EDIT_SETTIME_DTV3           1092
#define IDC_EDIT_TEST_ITEM              1093
#define IDC_EDIT_SETTIME_ATV1           1093
#define IDC_EDIT_TESTING                1094
#define IDC_EDIT_SETTIME_ATV2           1094
#define IDC_EDIT_SETTIME_DVBS           1095
#define IDC_EDIT_SETTIME_AV1            1096
#define IDC_MFCBUTTON_SOURCE            1097
#define IDC_EDIT_SETTIME_AV2            1097
#define IDC_MFCBUTTON_CHP               1098
#define IDC_EDIT_SETTIME_YPBPR          1098
#define IDC_MFCBUTTON_VOLP              1099
#define IDC_EDIT_SETTIME_HDMI1          1099
#define IDC_MFCBUTTON_VOLM              1100
#define IDC_EDIT_SETTIME_HDMI2          1100
#define IDC_MFCBUTTON_CHM               1101
#define IDC_EDIT_SETTIME_HDMI3          1101
#define IDC_MFCBUTTON_POWER             1102
#define IDC_EDIT_SETTIME_HDMI4          1102
#define IDC_MFCBUTTON_KEYPAD_RESUIT     1103
#define IDC_EDIT_SETTIME_SCART          1103
#define IDC_MFCBUTTON_MENU              1104
#define IDC_EDIT_SETTIME_PC             1104
#define IDC_STATIC_KEYPAD               1105
#define IDC_EDIT18                      1105
#define IDC_EDIT_SETTIME_USB            1105
#define IDC_STATIC_VERSION              1106
#define IDC_STATIC_DATA                 1107
#define IDC_STATIC_MAIN_VER             1108
#define IDC_STATIC_DELAY                1109
#define IDC_BUTTON_SETUP                1111
#define IDC_RADIO_7KEY                  1112
#define IDC_RADIO_5KAY                  1113
#define IDC_CHECK_DTV1                  1114
#define IDC_CHECK_DTV2                  1115
#define IDC_CHECK_DTV3                  1116
#define IDC_CHECK_ATV1                  1117
#define IDC_CHECK_ATV2                  1118
#define IDC_CHECK_DVBS                  1119
#define IDC_CHECK_AV1                   1120
#define IDC_CHECK_AV2                   1121
#define IDC_CHECK_HDMI1                 1122
#define IDC_CHECK_HDMI2                 1123
#define IDC_CHECK_HDMI3                 1124
#define IDC_CHECK1_HDMI4                1125
#define IDC_CHECK_SCART                 1126
#define IDC_CHECK_YPBPR                 1127
#define IDC_CHECK_PC                    1128
#define IDC_CHECK_USB                   1129
#define IDC_EDIT_SETUP_VERSION          1130
#define IDC_EDIT_JNUMBER                1131
#define IDC_EDIT_ORDER                  1132
#define IDC_COMBO_LINE                  1133
#define IDC_COMBO_DATA_READ             1134
#define IDC_COMBO_DATA_SECCLE           1135
#define IDC_COMBO_TestProject           1136
#define IDC_COMBO_MAINKEY               1137
#define IDC_CHECK_SN                    1138
#define IDC_EDIT_SN_DATA                1139
#define IDC_CHECK_MAC                   1140
#define IDC_EDIT_MAC_DATA               1141
#define IDC_EDIT_INTO_MESSAGE           1142
#define IDC_STATIC_SHOW_TIMER           1143
#define IDC_STATIC_SHOW_MESSAGE         1144
#define IDC_LIST_DATA                   1145
#define IDC_EDIT_MAINKEY                1146
#define IDC_STATIC_USBscan              1148
#define IDC_STATIC_chuankou             1149
#define IDC_STATIC_botelv               1150
#define IDC_STATIC_shujuwei             1151
#define IDC_STATIC_tingzhiwei           1152
#define IDC_STATIC_xiaoyanwei           1153
#define IDC_STATIC_ckkongzhi            1154
#define IDC_STATIC_gonghao              1155
#define IDC_STATIC_dingdanhao           1156
#define IDC_STATIC_gonggong             1157
#define IDC_STATIC_gonggong24           1157
#define IDC_STATIC_shujupeizhi          1158
#define IDC_STATIC_tongxunpeizhi        1159
#define IDC_STATIC_zhujianming          1160
#define IDC_STATIC_xianti               1161
#define IDC_STATIC_huoqushuju           1162
#define IDC_STATIC_jianyanshuju         1163
#define IDC_STATIC_ceshifangan          1164

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1165
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
